### PR TITLE
Bump shipwright-io/build to v0.5.0 (II)

### PR DESCRIPTION
**Pull request by HeavyWombat**
# Changes

Based on https://github.com/shipwright-io/cli/pull/19, but with an additional tweak for `client-go` in the Go modules files. Otherwise, just cherry-picked the commits by @adambkaplan and fixed the merge conflict in Go sum:
- Fix reporting of build run status
- Move client-go from replace to import
- Skip resource list unit test

# Submitter Checklist

- [X] Includes tests if functionality changed/was added
- [ ] Includes docs if changes are user-facing
- [X] [Set a kind label on this PR](https://prow.k8s.io/command-help#kind)  
- [X] Release notes block has been filled in, or marked NONE

See [the contributor guide](https://github.com/shipwright-io/build/blob/main/CONTRIBUTING.md)
for details on coding conventions, github and prow interactions, and the code review process.

# Release Notes

```release-note
NONE
```

### CODE REVIEW

**Comment by HeavyWombat** [comment]
I am currently working on the local source code EP and for this, I needed to play around with the CLI. For future updates, I would like to align the CLI a bit more to the current level of https://github.com/shipwright-io/build.

@otaviof @alicerum Going forward, I would like to propose to replace the dynamic client with the specific client. I have done that task in https://github.com/homeport/build-load some time ago and can offer to do the same here again.

**Review by SaschaSchwarze0 — APPROVED** [review]
/lgtm

**Comment by SaschaSchwarze0** [comment]
> @otaviof @alicerum Going forward, I would like to propose to replace the dynamic client with the specific client. I have done that task in https://github.com/homeport/build-load some time ago and can offer to do the same here again.

Hi @HeavyWombat you can go ahead with that. There is consensus on that aspect I'd say. The issue is [Review the Need for the Dynamic-Client #24](https://github.com/shipwright-io/cli/issues/24). It was also discussed in the [community meeting from June 21st](https://github.com/shipwright-io/build/issues/812#issuecomment-863327989).

**Comment by SaschaSchwarze0** [comment]
He @otaviof, @HeavyWombat rebased the commits from @adambkaplan from PR #19 that you had approved already. Can you approve this one?

**Review by adambkaplan — APPROVED** [review]
/approve

**Pull request merged**
