### PR TITLE
Configurable E2E Container Registry

### LINKED ISSUE #87: [E2E] Configurable Container Registry (Output-Image)
As a developer, I would like to use a different container registry to run Bats based end-to-end tests. For instance, on [this test case](https://github.com/shipwright-io/cli/blob/ca5ef319bd3d3449b3743b904fbf8e79e2047be9/test/e2e/log-follow--follow.bats#L22) we define the output image as:

```sh
--output-image=registry.registry.svc.cluster.local:32222/shipwright-io/build-e2e
```

However, during the development workflow, it's common to use a different container registry and if not properly configured the Bats tests will fail.

Ideally, we should have a single `function` to define the output image, and thus create the opportunity to modify the output-image accordingly.

### PR DESCRIPTION
**Pull request by otaviof**
# Changes

Making the container registry address used in end-to-end tests configurable, for instance:

```bash
make test-e2e OUTPUT_HOSTNAME="image-registry.openshift-image-registry.svc:5000" OUTPUT_NAMESPACE="otaviof"
```

And, the Container Registry can be deployed as:

```bash
make install-registry REGISTRY_NAMESPACE="otaviof"
```

Fixes #87 

# Submitter Checklist

- [x] ~Includes tests if functionality changed/was added~
- [x] ~Includes docs if changes are user-facing~
- [x] [Set a kind label on this PR](https://prow.k8s.io/command-help#kind)  
- [x] Release notes block has been filled in, or marked NONE

# Release Notes

```release-note
NONE
```

### CODE REVIEW

**Comment by otaviof** [comment]
@ricardomaraschini please consider, here we have a example of how to handle KinD with a container registry inside.

**Review by qu1queee — APPROVED** [review]
nice, thanks!
/lgtm

**Review by SaschaSchwarze0 — APPROVED** [review]
/approve

**Comment by otaviof** [comment]
Thank you, folks! 🙇

**Pull request merged**
