### PR TITLE
adjust shp build run -F e2e so that buildpacks build actually fully completes successfully

### LINKED ISSUE #57: see what shipwright/build e2e's do, fix buildpack integration in some of the new cli e2e's
See https://github.com/shipwright-io/cli/pull/56/files#diff-b3735b69bbdffbd0057392faad2520a70a01255bea7da053f2675836845d8869R28-R34

```
     [build-and-push] ERROR: No buildpack groups passed detection.
     [build-and-push] ERROR: Please check that you are running against the correct path.
     [build-and-push] ERROR: failed to detect: no buildpacks participating
```

### PR DESCRIPTION
**Pull request by gabemontero**
# Changes

Fixes #57

/kind cleanup

# Submitter Checklist

- [ /] Includes tests if functionality changed/was added
- [ n/a] Includes docs if changes are user-facing
- [ /] [Set a kind label on this PR](https://prow.k8s.io/command-help#kind)  
- [ /] Release notes block has been filled in, or marked NONE

See [the contributor guide](https://github.com/shipwright-io/build/blob/main/CONTRIBUTING.md)
for details on coding conventions, github and prow interactions, and the code review process.

# Release Notes

```release-note
NONE
```

### CODE REVIEW

**Comment by gabemontero** [comment]
/assign @coreydaley 
/assign @otaviof 

OK with the assists from @SaschaSchwarze0 / @HeavyWombat have the buildpack build working end to end in the e2e's

PTAL

the verify failure seems to be a new problem with github action golint .... sorting that our separately

**Review by SaschaSchwarze0 — APPROVED** [review]
/lgtm
/approve

**Comment by gabemontero** [comment]
FYI these changes also should address a data race we were seeing intermittently in the unit tests.  The race took the form of:

```
==================
WARNING: DATA RACE
Read at 0x00c0001967c0 by goroutine 12:
  github.com/shipwright-io/cli/pkg/shp/cmd/build.(*RunCommand).onEvent()
      /home/runner/work/cli/cli/pkg/shp/cmd/build/run.go:173 +0x1af
  github.com/shipwright-io/cli/pkg/shp/cmd/build.TestStartBuildRunFollowLog()
      /home/runner/work/cli/cli/pkg/shp/cmd/build/run_test.go:184 +0x1684
  testing.tRunner()
      /opt/hostedtoolcache/go/1.17.4/x64/src/testing/testing.go:1259 +0x22f
  testing.(*T).Run·dwrap·21()
      /opt/hostedtoolcache/go/1.17.4/x64/src/testing/testing.go:1306 +0x47

Previous write at 0x00c0001967c0 by goroutine 20:
  github.com/shipwright-io/cli/pkg/shp/cmd/build.(*RunCommand).Run()
      /home/runner/work/cli/cli/pkg/shp/cmd/build/run.go:237 +0x44c
  github.com/shipwright-io/cli/pkg/shp/cmd/build.TestStartBuildRunFollowLog.func3()
      /home/runner/work/cli/cli/pkg/shp/cmd/build/run_test.go:174 +0x59

Goroutine 12 (running) created at:
  testing.(*T).Run()
      /opt/hostedtoolcache/go/1.17.4/x64/src/testing/testing.go:1306 +0x726
  testing.runTests.func1()
      /opt/hostedtoolcache/go/1.17.4/x64/src/testing/testing.go:1598 +0x99
  testing.tRunner()
      /opt/hostedtoolcache/go/1.17.4/x64/src/testing/testing.go:1259 +0x22f
  testing.runTests()
      /opt/hostedtoolcache/go/1.17.4/x64/src/testing/testing.go:1596 +0x7ca
  testing.(*M).Run()
      /opt/hostedtoolcache/go/1.17.4/x64/src/testing/testing.go:1504 +0x9d1
  main.main()
      _testmain.go:101 +0x324

Goroutine 20 (running) created at:
  github.com/shipwright-io/cli/pkg/shp/cmd/build.TestStartBuildRunFollowLog()
      /home/runner/work/cli/cli/pkg/shp/cmd/build/run_test.go:173 +0x15c4
  testing.tRunner()
      /opt/hostedtoolcache/go/1.17.4/x64/src/testing/testing.go:1259 +0x22f
  testing.(*T).Run·dwrap·21()
      /opt/hostedtoolcache/go/1.17.4/x64/src/testing/testing.go:1306 +0x47
==================

```

That translated to these prior lines of code:
https://github.com/shipwright-io/cli/blob/d3e2e62e934fb5befbc040bad732998db640ae94/pkg/shp/cmd/build/run.go#L237
https://github.com/shipwright-io/cli/blob/d3e2e62e934fb5befbc040bad732998db640ae94/pkg/shp/cmd/build/run.go#L173

while the race seems artificial since https://github.com/shipwright-io/cli/blob/d3e2e62e934fb5befbc040bad732998db640ae94/pkg/shp/cmd/build/run.go#L173 should never get called until after https://github.com/shipwright-io/cli/blob/d3e2e62e934fb5befbc040bad732998db640ae94/pkg/shp/cmd/build/run.go#L247

this change further resolves things, as the setting of the struct's `buildRunName` was moved out of the `Run` method and into `NewFollower`

**Pull request merged**
