### PR TITLE
Fix dependencies

### PR DESCRIPTION
**Pull request by SaschaSchwarze0**
# Changes

Dependabot tricked me. The [Gomega update](https://github.com/shipwright-io/cli/pull/124) for some reason had here downgraded some packages. No idea why. It looked so good on [build](https://github.com/shipwright-io/build/pull/1083/files) and [operator](https://github.com/shipwright-io/operator/pull/86/files) that I was no careful enough reviewing it here. I learned my lesson.

Here I am correcting it.

# Submitter Checklist

- [ ] Includes tests if functionality changed/was added
- [ ] Includes docs if changes are user-facing
- [x] [Set a kind label on this PR](https://prow.k8s.io/command-help#kind)  
- [x] Release notes block has been filled in, or marked NONE

# Release Notes

```release-note
NONE
```

### CODE REVIEW

**Comment by otaviof** [comment]
/lgtm

Tested the changes here, they work as expected. Thanks @SaschaSchwarze0!

/assign @coreydaley

**Comment by coreydaley** [comment]
@otaviof I don't have approval rights here, you need someone in https://github.com/shipwright-io/cli/blob/main/OWNERS

**Pull request merged**
