### PR TITLE
Bump shipwright-io/build to v0.5.0

### PR DESCRIPTION
**Pull request by adambkaplan**
Now that v0.5.0 has been released, we need to bump the CLI's dependencies.

This includes a fix for the breaking change to BuildRun's status field.

### CODE REVIEW

**Comment by adambkaplan** [comment]
@alicerum it isn't at all clear to me why the list test is failing after the kube rebase:

```shell
=== RUN   TestResource/Resource_List
=== CONT  TestResource
    resource_test.go:52: 
        Error from List must be nil
        Expected
            <*errors.errorString | 0xc000538200>: {
                s: "item[0]: can't assign or convert unstructured.Unstructured into v1alpha1.Build",
            }
        to be nil
```

**Comment by adambkaplan** [comment]
Decided to skip the unit test - the fake dynamic client is pretty brittle and provided on an "as-is" basis.

https://github.com/kubernetes/client-go/issues/983

**Comment by otaviof** [comment]
An update about the issue found on this PR, when we start a fake dynamic-client with a Build object, it does `List` items without errors. On the following snippet we have a concise example of how the dynamic-client is employed, please consider:

```go
func TestSimpleDynamicClientList(t *testing.T) {
	g := gomega.NewGomegaWithT(t)

	scheme := runtime.NewScheme()
	buildv1alpha1.SchemeBuilder.AddToScheme(scheme)

	b := &buildv1alpha1.Build{}
	b.SetName("name")
        client := fake.NewSimpleDynamicClient(scheme, b)

	rs := client.Resource(buildv1alpha1.SchemeGroupVersion.WithResource("builds"))
	res, err := rs.List(context.TODO(), metav1.ListOptions{})
	g.Expect(err).To(gomega.BeNil())
	g.Expect(res).ToNot(gomega.BeNil())
	g.Expect(len(res.Items)).To(gomega.Equal(1))
}
```

**Comment by otaviof** [comment]
/lgtm

We will tackle the root-cause of the test skipped here, so the current state looks good to me.

**Comment by HeavyWombat** [comment]
Superseded by #34

**Pull request closed without merging**
